### ISSUE TITLE
请问栏目内有较多内容时，是否有考虑加入  点击加入一个dialog内容呢？

### ISSUE THREAD

**Issue by cmy471520959** [Peng-Xiao-Shuai-0902/el-plus-powerful-table#1]
请问栏目内有较多内容时，是否有考虑加入  点击加入一个dialog内容呢？

**Comment by chenle1005** [comment]
请问是想要用dialog显示当前行的数据还是某个内容较多的单元格的数据？

**Comment by peng-xiao-shuai** [comment]
> 好像栏目内有话题内容时，是否有考虑加入一个对话内容呢？

这个暂时没有其他开发人员有这个需求，其他特殊业务可以使用slot
