### ISSUE TITLE
引入powerful-table组件就出现warn死循环

### ISSUE THREAD

**Issue by faruzanCN** [Peng-Xiao-Shuai-0902/el-plus-powerful-table#3]
warn提示Unhandled error during execution of scheduler flush. 
"vue": "^3.2.33",
"element-plus": "^2.2.0",

**Comment by peng-xiao-shuai** [comment]
你可以提供一个demo地址？以便我们可以更好的判断问题所在

**Comment by peng-xiao-shuai** [comment]
> 警告提示执行调度程序刷新期间出现未处理的错误。 “vue”：“^3.2.33”， “元素加”：“^2.2.0”，

你可以提供一个demo地址？以便我们可以更好的判断问题所在
